
#USA UMA IMAGEM OFICIAL E LEVE DO PYTHON
FROM python:3.9-slim

# DEFINE A PASTA DE TRABALHO DENTRO DO CONTÊINER
WORKDIR /app

#COPIA OS REQUISITOS E INSTALAR AS BIBLIOTECAS NECESSÁRIAS
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#COPIA O RESTANTE DO CODIGO
COPY . .

#EXPÕE A PORTA 5000
EXPOSE 5000

#DEFINE O COMANDO PARA EXECUTAR O SCRIPT
CMD ["python", "webhook_receiver.py"]
